<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-15 22:51
=======
# Generated by Django 4.2.7 on 2023-11-15 18:19
>>>>>>> 0427a346f88c86189d5c71ff6f82763ad738f8c4

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Sucursalesinfo',
=======
            name='Sucursales',
>>>>>>> 0427a346f88c86189d5c71ff6f82763ad738f8c4
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_servicios', models.CharField(max_length=60)),
            ],
        ),
    ]
