# Generated by Django 4.2.7 on 2023-11-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='direccion',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='nombre_medico',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
